export const ON_HTTP_ERROR = 'httperror'
export const UPDATE_LAST_HTTP_OBJECT = 'lasthttpreq'
export const HTTP_IS_IN_PROGRESS = 'httpinprogress'
export const HTTP_COMPLETED = 'httpcompleted'
export const NOTIFY_WITH = 'notifywith'
export const LOGOUT_ACTION = 'logoutAction'